version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5

    steps:
      - checkout

      - run:
          name: Install gems
          command: bundle install

      - run:
          name: Run tests
          command: rake test --trace
